//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 11:42:23 AM IST 
//


package com.xchanging.xsb.premiumact.jaxb.workorder.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ReferredTechAccountUUId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferredTechAccountServiceProviderReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PegaWO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TechAccountUUId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Application" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorkOrderUniqueId" type="{}WorkOrderUniqueIdType"/>
 *         &lt;element name="UrgentReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrokerContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrokerContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrokerContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Broker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UMR" type="{}UMRType"/>
 *         &lt;element name="TypeOfSubmission" type="{}TypeOfSubmissionType"/>
 *         &lt;element name="Market" type="{}MarketType"/>
 *         &lt;element name="ClassOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SlipType" type="{}SlipTypeType"/>
 *         &lt;element name="TypeOfPolicy" type="{}TypeOfPolicyType" minOccurs="0"/>
 *         &lt;element name="ProcessingRequired" type="{}ProcessingRequiredType"/>
 *         &lt;element name="PremiumFDOLPANS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="APRPLPANS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="XISContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdditionalDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PresentationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorkOrderReference" type="{}WorkOrderReferenceType"/>
 *         &lt;element name="GroupReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberInGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UCR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SimSigningRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TreatyFdoStatement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="XisScanned" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Urgent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="trackerBarcode" type="{}trackerBarcodeType"/>
 *         &lt;element name="logisticsInView" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logisticsOutView" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="techniciansView" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workPackageView" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}DocumentsType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "WorkOrder")
public class WorkOrder {

    @XmlElement(name = "ReferredTechAccountUUId")
    protected String referredTechAccountUUId;
    @XmlElement(name = "ReferredTechAccountServiceProviderReference")
    protected String referredTechAccountServiceProviderReference;
    @XmlElement(name = "PegaWO")
    protected String pegaWO;
    @XmlElement(name = "TechAccountUUId", required = true)
    protected String techAccountUUId;
    @XmlElement(name = "Application", required = true)
    protected String application;
    @XmlElement(name = "WorkOrderUniqueId", required = true)
    protected String workOrderUniqueId;
    @XmlElement(name = "UrgentReference", required = true)
    protected String urgentReference;
    @XmlElement(name = "BrokerContactName", required = true)
    protected String brokerContactName;
    @XmlElement(name = "BrokerContactPhone", required = true)
    protected String brokerContactPhone;
    @XmlElement(name = "BrokerContactEmail", required = true)
    protected String brokerContactEmail;
    @XmlElement(name = "Broker", required = true)
    protected String broker;
    @XmlElement(name = "UMR", required = true)
    protected String umr;
    @XmlElement(name = "TypeOfSubmission", required = true)
    protected String typeOfSubmission;
    @XmlElement(name = "Market", required = true)
    @XmlSchemaType(name = "string")
    protected MarketType market;
    @XmlElement(name = "ClassOfBusiness", required = true)
    protected String classOfBusiness;
    @XmlElement(name = "SlipType", required = true)
    @XmlSchemaType(name = "string")
    protected SlipTypeType slipType;
    @XmlElement(name = "TypeOfPolicy")
    protected String typeOfPolicy;
    @XmlElement(name = "ProcessingRequired", required = true)
    protected String processingRequired;
    @XmlElement(name = "PremiumFDOLPANS", required = true)
    protected String premiumFDOLPANS;
    @XmlElement(name = "APRPLPANS", required = true)
    protected String aprplpans;
    @XmlElement(name = "XISContactName", required = true)
    protected String xisContactName;
    @XmlElement(name = "AdditionalDetails", required = true)
    protected String additionalDetails;
    @XmlElement(name = "PresentationDate", required = true)
    protected String presentationDate;
    @XmlElement(name = "WorkOrderReference", required = true)
    protected String workOrderReference;
    @XmlElement(name = "GroupReference", required = true)
    protected String groupReference;
    @XmlElement(name = "NumberInGroup", required = true)
    protected String numberInGroup;
    @XmlElement(name = "UCR", required = true)
    protected String ucr;
    @XmlElement(name = "TR", required = true)
    protected String tr;
    @XmlElement(name = "SimSigningRequired", required = true)
    protected String simSigningRequired;
    @XmlElement(name = "TreatyFdoStatement", required = true)
    protected String treatyFdoStatement;
    @XmlElement(name = "XisScanned", required = true)
    protected String xisScanned;
    @XmlElement(name = "Urgent")
    protected Boolean urgent;
    @XmlElement(required = true)
    protected String trackerBarcode;
    @XmlElement(required = true)
    protected String logisticsInView;
    @XmlElement(required = true)
    protected String logisticsOutView;
    @XmlElement(required = true)
    protected String techniciansView;
    @XmlElement(required = true)
    protected String workPackageView;
    @XmlElementRef(name = "DocumentsType", type = JAXBElement.class)
    protected JAXBElement<?> documentsType;

    /**
     * Gets the value of the referredTechAccountUUId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferredTechAccountUUId() {
        return referredTechAccountUUId;
    }

    /**
     * Sets the value of the referredTechAccountUUId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferredTechAccountUUId(String value) {
        this.referredTechAccountUUId = value;
    }

    /**
     * Gets the value of the referredTechAccountServiceProviderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferredTechAccountServiceProviderReference() {
        return referredTechAccountServiceProviderReference;
    }

    /**
     * Sets the value of the referredTechAccountServiceProviderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferredTechAccountServiceProviderReference(String value) {
        this.referredTechAccountServiceProviderReference = value;
    }

    /**
     * Gets the value of the pegaWO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPegaWO() {
        return pegaWO;
    }

    /**
     * Sets the value of the pegaWO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPegaWO(String value) {
        this.pegaWO = value;
    }

    /**
     * Gets the value of the techAccountUUId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechAccountUUId() {
        return techAccountUUId;
    }

    /**
     * Sets the value of the techAccountUUId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechAccountUUId(String value) {
        this.techAccountUUId = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the workOrderUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkOrderUniqueId() {
        return workOrderUniqueId;
    }

    /**
     * Sets the value of the workOrderUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkOrderUniqueId(String value) {
        this.workOrderUniqueId = value;
    }

    /**
     * Gets the value of the urgentReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrgentReference() {
        return urgentReference;
    }

    /**
     * Sets the value of the urgentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrgentReference(String value) {
        this.urgentReference = value;
    }

    /**
     * Gets the value of the brokerContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerContactName() {
        return brokerContactName;
    }

    /**
     * Sets the value of the brokerContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerContactName(String value) {
        this.brokerContactName = value;
    }

    /**
     * Gets the value of the brokerContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerContactPhone() {
        return brokerContactPhone;
    }

    /**
     * Sets the value of the brokerContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerContactPhone(String value) {
        this.brokerContactPhone = value;
    }

    /**
     * Gets the value of the brokerContactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerContactEmail() {
        return brokerContactEmail;
    }

    /**
     * Sets the value of the brokerContactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerContactEmail(String value) {
        this.brokerContactEmail = value;
    }

    /**
     * Gets the value of the broker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroker() {
        return broker;
    }

    /**
     * Sets the value of the broker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroker(String value) {
        this.broker = value;
    }

    /**
     * Gets the value of the umr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUMR() {
        return umr;
    }

    /**
     * Sets the value of the umr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUMR(String value) {
        this.umr = value;
    }

    /**
     * Gets the value of the typeOfSubmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfSubmission() {
        return typeOfSubmission;
    }

    /**
     * Sets the value of the typeOfSubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfSubmission(String value) {
        this.typeOfSubmission = value;
    }

    /**
     * Gets the value of the market property.
     * 
     * @return
     *     possible object is
     *     {@link MarketType }
     *     
     */
    public MarketType getMarket() {
        return market;
    }

    /**
     * Sets the value of the market property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketType }
     *     
     */
    public void setMarket(MarketType value) {
        this.market = value;
    }

    /**
     * Gets the value of the classOfBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassOfBusiness() {
        return classOfBusiness;
    }

    /**
     * Sets the value of the classOfBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassOfBusiness(String value) {
        this.classOfBusiness = value;
    }

    /**
     * Gets the value of the slipType property.
     * 
     * @return
     *     possible object is
     *     {@link SlipTypeType }
     *     
     */
    public SlipTypeType getSlipType() {
        return slipType;
    }

    /**
     * Sets the value of the slipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SlipTypeType }
     *     
     */
    public void setSlipType(SlipTypeType value) {
        this.slipType = value;
    }

    /**
     * Gets the value of the typeOfPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfPolicy() {
        return typeOfPolicy;
    }

    /**
     * Sets the value of the typeOfPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfPolicy(String value) {
        this.typeOfPolicy = value;
    }

    /**
     * Gets the value of the processingRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingRequired() {
        return processingRequired;
    }

    /**
     * Sets the value of the processingRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingRequired(String value) {
        this.processingRequired = value;
    }

    /**
     * Gets the value of the premiumFDOLPANS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiumFDOLPANS() {
        return premiumFDOLPANS;
    }

    /**
     * Sets the value of the premiumFDOLPANS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiumFDOLPANS(String value) {
        this.premiumFDOLPANS = value;
    }

    /**
     * Gets the value of the aprplpans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPRPLPANS() {
        return aprplpans;
    }

    /**
     * Sets the value of the aprplpans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPRPLPANS(String value) {
        this.aprplpans = value;
    }

    /**
     * Gets the value of the xisContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXISContactName() {
        return xisContactName;
    }

    /**
     * Sets the value of the xisContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXISContactName(String value) {
        this.xisContactName = value;
    }

    /**
     * Gets the value of the additionalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalDetails() {
        return additionalDetails;
    }

    /**
     * Sets the value of the additionalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalDetails(String value) {
        this.additionalDetails = value;
    }

    /**
     * Gets the value of the presentationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationDate() {
        return presentationDate;
    }

    /**
     * Sets the value of the presentationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationDate(String value) {
        this.presentationDate = value;
    }

    /**
     * Gets the value of the workOrderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkOrderReference() {
        return workOrderReference;
    }

    /**
     * Sets the value of the workOrderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkOrderReference(String value) {
        this.workOrderReference = value;
    }

    /**
     * Gets the value of the groupReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupReference() {
        return groupReference;
    }

    /**
     * Sets the value of the groupReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupReference(String value) {
        this.groupReference = value;
    }

    /**
     * Gets the value of the numberInGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberInGroup() {
        return numberInGroup;
    }

    /**
     * Sets the value of the numberInGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberInGroup(String value) {
        this.numberInGroup = value;
    }

    /**
     * Gets the value of the ucr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCR() {
        return ucr;
    }

    /**
     * Sets the value of the ucr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCR(String value) {
        this.ucr = value;
    }

    /**
     * Gets the value of the tr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTR() {
        return tr;
    }

    /**
     * Sets the value of the tr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTR(String value) {
        this.tr = value;
    }

    /**
     * Gets the value of the simSigningRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimSigningRequired() {
        return simSigningRequired;
    }

    /**
     * Sets the value of the simSigningRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimSigningRequired(String value) {
        this.simSigningRequired = value;
    }

    /**
     * Gets the value of the treatyFdoStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreatyFdoStatement() {
        return treatyFdoStatement;
    }

    /**
     * Sets the value of the treatyFdoStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreatyFdoStatement(String value) {
        this.treatyFdoStatement = value;
    }

    /**
     * Gets the value of the xisScanned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXisScanned() {
        return xisScanned;
    }

    /**
     * Sets the value of the xisScanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXisScanned(String value) {
        this.xisScanned = value;
    }

    /**
     * Gets the value of the urgent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUrgent() {
        return urgent;
    }

    /**
     * Sets the value of the urgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUrgent(Boolean value) {
        this.urgent = value;
    }

    /**
     * Gets the value of the trackerBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackerBarcode() {
        return trackerBarcode;
    }

    /**
     * Sets the value of the trackerBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackerBarcode(String value) {
        this.trackerBarcode = value;
    }

    /**
     * Gets the value of the logisticsInView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticsInView() {
        return logisticsInView;
    }

    /**
     * Sets the value of the logisticsInView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticsInView(String value) {
        this.logisticsInView = value;
    }

    /**
     * Gets the value of the logisticsOutView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticsOutView() {
        return logisticsOutView;
    }

    /**
     * Sets the value of the logisticsOutView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticsOutView(String value) {
        this.logisticsOutView = value;
    }

    /**
     * Gets the value of the techniciansView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechniciansView() {
        return techniciansView;
    }

    /**
     * Sets the value of the techniciansView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechniciansView(String value) {
        this.techniciansView = value;
    }

    /**
     * Gets the value of the workPackageView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPackageView() {
        return workPackageView;
    }

    /**
     * Sets the value of the workPackageView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPackageView(String value) {
        this.workPackageView = value;
    }

    /**
     * Gets the value of the documentsType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link Documents }{@code >}
     *     
     */
    public JAXBElement<?> getDocumentsType() {
        return documentsType;
    }

    /**
     * Sets the value of the documentsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link Documents }{@code >}
     *     
     */
    public void setDocumentsType(JAXBElement<?> value) {
        this.documentsType = value;
    }

}
